from __future__ import annotations

import hashlib
from typing import Any, Mapping

from .contract import collect_operations, fixed_http_method_fields
from .markdown import (
    contract_servers,
    operation_servers,
    render_parameters,
    render_request_body,
    render_responses,
    render_security_schemes,
)
from .markdown_common import code, compact_text, quote_block, security_summary


def render_catalog(spec: Mapping[str, Any], raw: bytes, source_name: str) -> str:
    """Render a deterministic Markdown operation catalog."""

    operations = collect_operations(spec)
    metadata = _catalog_metadata(spec, raw, source_name, operations)
    global_security = spec.get("security")

    lines = _catalog_header(
        metadata,
        operations,
    )
    lines.extend(_catalog_servers_and_security(spec, global_security))
    lines.extend(_catalog_operation_index(operations))
    lines.extend(["", "## Operation details", ""])
    for index, operation in enumerate(operations, start=1):
        lines.extend(_catalog_operation_details(index, operation, spec, global_security))
    return "\n".join(lines).rstrip() + "\n"


def _catalog_metadata(
    spec: Mapping[str, Any], raw: bytes, source_name: str, operations: list[Any]
) -> dict[str, Any]:
    info = _catalog_info(spec)
    fixed_methods = {item.upper() for item in fixed_http_method_fields(spec)}
    return {
        "title": compact_text(info.get("title"), default="Relution"),
        "info_version": compact_text(info.get("version"), default="not declared"),
        "contract_version": spec.get("openapi") or spec.get("swagger"),
        "contract_kind": "OpenAPI" if spec.get("openapi") else "Swagger",
        "digest": hashlib.sha256(raw).hexdigest(),
        "source_name": source_name,
        "path_count": len(spec.get("paths") or {}),
        "webhook_count": len(spec.get("webhooks") or {}),
        "callback_count": sum(item.surface == "callbacks" for item in operations),
        "additional_count": sum(item.method.upper() not in fixed_methods for item in operations),
    }


def _catalog_info(spec: Mapping[str, Any]) -> Mapping[str, Any]:
    info = spec.get("info")
    return info if isinstance(info, Mapping) else {}


def _catalog_header(metadata: Mapping[str, Any], operations: list[Any]) -> list[str]:
    return [
        f"# {metadata['title']} API operation catalog",
        "",
        "> Generated by `scripts/render_relution_openapi.py`. Do not edit by hand.",
        "> The source JSON remains authoritative for complete schema constraints.",
        "",
        f"- Contract format: **{metadata['contract_kind']} {compact_text(metadata['contract_version'])}**",
        f"- API info version: **{metadata['info_version']}**",
        f"- Source file: `{compact_text(metadata['source_name'])}`",
        f"- Source SHA-256: `{metadata['digest']}`",
        f"- Paths: **{metadata['path_count']}**",
        f"- Webhooks: **{metadata['webhook_count']}**",
        f"- Callback operations: **{metadata['callback_count']}**",
        f"- Additional-method operations: **{metadata['additional_count']}**",
        f"- Operations: **{len(operations)}**",
        "",
        "## Completeness and use",
        "",
        "This file enumerates every Operation Object reachable beneath top-level "
        "`paths`, `webhooks`, and recursive callbacks in the supplied contract, "
        "including OpenAPI 3.2 `query` and `additionalOperations`. Local path-item "
        "and callback references are resolved; generation fails for external "
        "operation-bearing references or malformed entries so operations are not "
        "silently omitted.",
        "",
        "Before a live call, confirm the target host/version and this digest, then "
        "inspect the original JSON for full schemas, examples, extensions, and constraints. "
        "Catalog presence does not prove runtime permission, licensing, or authorization.",
        "",
        "## Contract servers",
        "",
    ]


def _catalog_servers_and_security(spec: Mapping[str, Any], global_security: Any) -> list[str]:

    lines: list[str] = []
    servers = contract_servers(spec)
    if servers:
        lines.extend(f"- {server}" for server in servers)
    else:
        lines.append(
            "No contract-level server declared. Confirm the authorized base URL separately."
        )

    lines.extend(
        [
            "",
            "## Security schemes",
            "",
            *render_security_schemes(spec),
            "",
            f"Global security requirement: {security_summary(global_security)}",
        ]
    )
    return lines


def _catalog_operation_index(operations: list[Any]) -> list[str]:
    lines = [
        "",
        "## Operation index",
        "",
        "| # | Surface | Method | Path/name | Operation ID | Tags | Summary |",
        "| ---: | --- | --- | --- | --- | --- | --- |",
    ]
    for index, operation in enumerate(operations, start=1):
        details = operation.operation
        tags = details.get("tags") or []
        tag_text = ", ".join(str(tag) for tag in tags) if isinstance(tags, list) else tags
        lines.append(
            "| "
            + " | ".join(
                (
                    str(index),
                    code(operation.surface),
                    code(operation.method),
                    code(operation.path),
                    code(details.get("operationId")),
                    compact_text(tag_text),
                    compact_text(details.get("summary")),
                )
            )
            + " |"
        )

    if not operations:
        lines.append(
            "| Not provided | Not provided | Not provided | Not provided | "
            "Not provided | Not provided | No operations declared |"
        )

    return lines


def _catalog_operation_details(
    index: int, operation: Any, spec: Mapping[str, Any], global_security: Any
) -> list[str]:
    details = operation.operation
    tags = details.get("tags") or []
    tag_text = (
        ", ".join(f"`{tag}`" for tag in tags) or "Not provided"
        if isinstance(tags, list)
        else compact_text(tags)
    )
    lines = [
        f"### {index}. {compact_text(operation.method)} {compact_text(operation.path)}",
        "",
        f"- Surface: `{operation.surface}`",
        *([f"- Callback lineage: {compact_text(operation.lineage)}"] if operation.lineage else []),
        f"- Operation ID: {code(details.get('operationId'))}",
        f"- Tags: {tag_text}",
        f"- Summary: {compact_text(details.get('summary'))}",
        f"- Deprecated: {'yes' if details.get('deprecated') is True else 'no'}",
        f"- Security: {security_summary(details.get('security', global_security))}",
        f"- Server override: {operation_servers(operation, spec)}",
    ]
    lines.extend(_catalog_optional_notes(details))
    lines.extend(
        [
            "",
            "#### Parameters",
            "",
            *render_parameters(operation),
            "",
            "#### Request body",
            "",
            *render_request_body(operation, spec),
            "",
            "#### Responses",
            "",
            *render_responses(operation, spec),
        ]
    )
    lines.extend(_catalog_callbacks(details))
    return lines + [""]


def _catalog_optional_notes(details: Mapping[str, Any]) -> list[str]:
    external_docs = details.get("externalDocs")
    description = quote_block(details.get("description"))
    return (
        [f"- External docs: {code(external_docs.get('url'))}"]
        if isinstance(external_docs, Mapping) and external_docs.get("url")
        else []
    ) + (["", *description] if description else [])


def _catalog_callbacks(details: Mapping[str, Any]) -> list[str]:
    callbacks = details.get("callbacks")
    if not isinstance(callbacks, Mapping) or not callbacks:
        return []
    return [
        "",
        "#### Callbacks",
        "",
        "Declared callback names/references: " + ", ".join(code(name) for name in callbacks),
        "",
        "Their Operation Objects are enumerated as separate `callbacks` entries with parent lineage. They are server-initiated callbacks, not top-level client-callable operations.",
    ]
