/** Provides small, sanitized fixtures that exercise the workbench without local files. */
import type { BsiRecommendationRecord, RecommendationCatalogResponse, RecommendationRecord } from "../../../src/browser/assurance.js";
import type { AppState } from "../shared/editor-contracts.js";

const generatedAt = "2026-08-31T09:00:00.000Z";

export function createDemoAppState(): AppState {
  return {
    revision: "demo-r1",
    bundle: { serverVersion: "26.1.1 · demo", sourceImage: "Sanitized Pages fixture", generatedAt, refreshDiagnostics: { runtimeMetadata: { source: "heuristic", reflectedCount: 0, configurationTypeCount: 3 }, iosSystemAppsLoaded: false, springConfigurationMetadataLoaded: false }, platforms: ["IOS"], enrollmentTypes: ["DEVICE"], configurationTypes: [passcodeTemplate(), restrictionTemplate(), networkTemplate()], schemas: {}, iosSystemApps: {}, springConfigurationMetadata: {} },
    workspace: { metadata: { name: "Northwind iOS security baseline", mode: "demo", updatedAt: generatedAt }, report: { generatedAt, evidence: ["BSI SYS.3.2.1", "CIS Apple iOS 17", "Apple Platform Deployment"] }, policies: [
      policy("ios-executive.json", "Executive iPhone baseline", "Managed iPhones with enforced passcode and sharing posture.", [configuration("IOS_PASSCODE", "passcode-executive", { enabled: true, forcePIN: true, allowSimple: false, minLength: 8, maxFailedAttempts: 8, maxInactivityMinutes: 5 }), configuration("IOS_RESTRICTION", "restriction-executive", { allowCloudBackup: false, allowAirDrop: false, allowScreenShot: true, forceEncryptedBackup: true }), configuration("IOS_WIFI", "wifi-executive", { ssid: "Northwind Secure", hiddenNetwork: false, autoJoin: true })]),
      policy("ios-shared.json", "Shared iPad assessment", "Representative shared-device controls with review-ready evidence.", [configuration("IOS_PASSCODE", "passcode-shared", { enabled: true, forcePIN: true, allowSimple: false, minLength: 6, maxFailedAttempts: 10, maxInactivityMinutes: 2 }), configuration("IOS_RESTRICTION", "restriction-shared", { allowCloudBackup: false, allowAirDrop: false, allowScreenShot: false, forceEncryptedBackup: true })]),
      policy("ios-research.json", "Research iPhone pilot", "Pilot controls ready for policy-owner review.", [configuration("IOS_WIFI", "wifi-research", { ssid: "Research-MDM", hiddenNetwork: true, autoJoin: true })]),
    ] },
    validation: { ok: true, errors: [], schemaCompatibilityIssueCount: 0 }, outputFile: "demo/exports/northwind-ios-baseline.rexp", keySet: false, keyValidated: false, keyValidationReason: "Archive keys are intentionally unavailable in the hosted demo.",
    appleCompat: { summary: { totalJamfGapSettings: 3, mobileconfigBacked: 2, notMobileconfigWireable: 1, relutionHasMobileconfigTransport: true, relutionMobileconfigPlatforms: ["IOS"] }, sources: ["Sanitized Apple compatibility evidence"], settings: [] },
    appleSchema: { version: 1, source: { repository: "apple/device-management", revision: "demo-sanitized", generatedAt }, counts: { profile: 1, "ddm-configuration": 0, "ddm-asset": 0, "ddm-activation": 0, "ddm-management": 0, "ddm-status": 0, "mdm-command": 1, "mdm-checkin": 0, "ddm-protocol": 0 }, entries: [{ id: "com.apple.mobiledevice.passwordpolicy", kind: "profile", title: "Passcode policy", description: "Sanitized Apple profile reference.", identifier: "com.apple.mobiledevice.passwordpolicy", sourcePath: "demo/apple/passcode.json", availability: { platforms: ["IOS"], allowMultiple: false, requiresMdm: true, deprecated: false, notes: ["Demo evidence only"] }, deprecated: false, fields: [] }] },
    sidecar: { version: 1, appleSchemaRevision: "demo-sanitized", mobileConfigRestore: [], ddmArtifacts: [], mdmCommandArtifacts: [{ uuid: "demo-device-information", schemaId: "DeviceInformation", kind: "mdm-command", requestType: "DeviceInformation", title: "Device information assessment", values: {}, payload: { RequestType: "DeviceInformation" } }], customManifests: [] },
  } as unknown as AppState;
}

export function demoRecommendationIndex(): unknown { return { sources: [recommendationSummary("bsi", "BSI Grundschutz"), recommendationSummary("cis", "CIS Apple iOS Benchmark"), recommendationSummary("vendor", "Apple deployment guidance")] }; }

export function demoRecommendationCatalog(source: string): RecommendationCatalogResponse {
  const summary = recommendationSummary(source === "cis" || source === "vendor" ? source : "bsi", source === "cis" ? "CIS Apple iOS Benchmark" : source === "vendor" ? "Apple deployment guidance" : "BSI Grundschutz");
  return { ...summary, recommendations: [recommendation(summary.source)], ruleset: demoBaselineRuleset() };
}

export function demoBaselineOptions(): unknown { return { version: 1, format: "demo", platforms: ["IOS"], shapes: ["modules", "full"], tiers: [1, 2, 3], options: [{ platform: "IOS", shape: "modules", tier: 2, tierLabel: "Tier 2 - strengthened iOS baseline", securityLevel: "standard-hardening", sourcePolicy: "Northwind iOS", coverage: "distinct", policyCount: 3, ruleCount: 9, actionableRuleCount: 6, informationalRuleCount: 3, suppressedConflictRuleCount: 1, stakeholderExamples: ["Research", "Executive"] }] }; }
export function demoBaselineExpertOptions(): unknown { return { version: 1, format: "demo", platform: "IOS", shape: "modules", tiers: [1, 2, 3], tierCoverage: [{ tier: 2, totalSettings: 1 }], settings: [{ id: "demo-passcode", label: "Strong passcode", policyName: "Executive iPhone baseline", ruleId: "DEMO-PASSCODE", ruleTitle: "Require strong passcode", requiredInTiers: [1, 2], tierMappings: [{ tier: 2, mappings: [{ kind: "relution-native", target: "IOS_PASSCODE", type: "IOS_PASSCODE", values: { enabled: true, forcePIN: true, minLength: 8 } }] }], recommendations: [{ source: "bsi", ruleId: "SYS.3.2.1", title: "Strong device passcode", sourceIds: ["SYS.3.2.1"] }] }] }; }
export function demoBaselineRuleset() { return { version: 1, name: "Hosted iOS baseline", policies: [{ platform: "IOS", name: "Hosted baseline preview", description: "A deterministic baseline assembled from sanitized evidence.", rules: [{ id: "demo-passcode", title: "Strong passcode", informational: false, sourceIds: ["SYS.3.2.1"], sourceRules: [], mappings: [{ kind: "relution-native", type: "IOS_PASSCODE", values: { enabled: true, forcePIN: true, minLength: 8 } }] }] }] }; }
export function demoComplianceReport(workspace: AppState["workspace"], policyIndex = 0, versionIndex = 0): unknown {
  const policy = workspace.policies[policyIndex] ?? workspace.policies[0]!;
  return { policyPath: policy.path, policyName: policy.document.name, policyPlatform: "IOS", versionIndex, sources: ["bsi", "cis", "vendor"], warnings: ["All evidence is sanitized and deterministic for the hosted demo."], results: [{ id: "demo-compliance-passcode", source: "bsi", recommendationId: "bsi-ios-passcode", recommendation: recommendation("bsi"), status: "compliant", mappingResults: [{ kind: "relution-native", target: "IOS_PASSCODE", status: "match", detail: "minLength 8 and forcePIN are configured." }], matchedConfigurations: [{ configurationIndex: 0, type: "IOS_PASSCODE", label: "iOS Passcode" }], blockingReasons: [], remediationOptions: [] }, { id: "demo-compliance-airdrop", source: "cis", recommendationId: "cis-ios-airdrop", recommendation: recommendation("cis"), status: "exact-gap", mappingResults: [], matchedConfigurations: [], blockingReasons: ["Review required for departmental sharing exception."], remediationOptions: [{ id: "demo-airdrop-off", title: "Disable AirDrop", description: "Apply the deterministic demo remediation.", available: true }] }], summary: { totalRecommendations: 2, byStatus: { compliant: 1, "exact-gap": 1, "choice-required": 0, "parameter-required": 0, "not-checkable": 0 } } };
}

function policy(path: string, name: string, description: string, configurations: unknown[]) { return { path: `policies/${path}`, document: { name, description, platform: "IOS", versions: [{ name: "2026.08 review", configurations }] } }; }
function configuration(type: string, uuid: string, values: Record<string, unknown>) { return { uuid, details: { uuid, type, ...values } }; }
function bsiRecommendation(source: "bsi" | "cis" | "vendor"): BsiRecommendationRecord { return { id: `${source}-ios-passcode`, platform: "IOS", title: "Require a strong device passcode", sourceIds: ["SYS.3.2.1", "CIS-1.2"], osFamily: "iOS", policyName: "Device passcode", moduleId: "SYS.3.2.1", moduleTitle: "Smartphones and tablets", category: "Device hardening", requirementId: "DEMO-01", status: "implemented", protectionLevel: "standard", actors: ["Policy owner"], paragraphs: ["A strong device passcode protects locally stored work data."], requirementText: "Require a strong device passcode.", reason: "Sanitized evidence for interactive review.", descriptionContext: ["Hosted demonstration"], checklistThreatIds: ["T-DEMO-01"], checklistThreatTitles: ["Loss of unmanaged access"], moduleThreatContext: [], errata: [], supportingSourceIds: [], relutionMapping: { status: "exact", mergeableInImportableRuleset: true, candidates: [{ kind: "relution-native", target: "IOS_PASSCODE", fieldPaths: ["minLength", "forcePIN"] }], rulesetMappings: [{ kind: "relution-native", type: "IOS_PASSCODE", values: { enabled: true, forcePIN: true, minLength: 8 } }], notes: ["Mapped to the demonstrated iOS passcode configuration."] }, implementation: { category: "relution-achievable", surfaces: ["relution-native"], importableVia: ["ruleset-import"], blockingReasons: [] } }; }
function recommendationSummary(source: "bsi" | "cis" | "vendor", label: string) { return { source, label, available: true, verifiedAsOf: "2026-08-31", recommendationCount: 1, coverageSummary: { exactMappings: 1, actionableRecommendations: 1, partialRecommendations: 0, helperOnlyRecommendations: 0, gapRecommendations: 0 }, displayPlatforms: ["IOS"], importPlatforms: ["IOS"], displayToImportPlatform: { IOS: "IOS" } }; }
function passcodeTemplate() { return template("IOS_PASSCODE", "iOS Passcode", "iOSPasscode", [{ path: "enabled", label: "Enforce passcode", kind: "boolean", defaultValue: true }, { path: "forcePIN", label: "Require PIN", kind: "boolean", defaultValue: true }, { path: "allowSimple", label: "Allow simple passcode", kind: "boolean", defaultValue: false }, { path: "minLength", label: "Minimum length", kind: "integer", defaultValue: 8 }, { path: "maxFailedAttempts", label: "Maximum failed attempts", kind: "integer", defaultValue: 8 }, { path: "maxInactivityMinutes", label: "Maximum inactivity", kind: "integer", defaultValue: 5 }]); }
function restrictionTemplate() { return template("IOS_RESTRICTION", "iOS Restrictions", "iOSRestriction", [{ path: "allowCloudBackup", label: "Allow cloud backup", kind: "boolean", defaultValue: false }, { path: "allowAirDrop", label: "Allow AirDrop", kind: "boolean", defaultValue: false }, { path: "allowScreenShot", label: "Allow screenshots", kind: "boolean", defaultValue: true }, { path: "forceEncryptedBackup", label: "Require encrypted backup", kind: "boolean", defaultValue: true }]); }
function networkTemplate() { return template("IOS_WIFI", "iOS Wi-Fi", "iOSWifi", [{ path: "ssid", label: "Network name", kind: "string", defaultValue: "" }, { path: "hiddenNetwork", label: "Hidden network", kind: "boolean", defaultValue: false }, { path: "autoJoin", label: "Auto-join", kind: "boolean", defaultValue: true }]); }
function template(type: string, label: string, schemaName: string, fields: Array<Record<string, unknown>>) { return { type, label, description: "Sanitized demo configuration with editable fields.", descriptionSource: "generated", schemaName, platforms: ["IOS"], enrollmentTypes: ["DEVICE"], multiConfig: false, portalHidden: false, placeholders: [], required: [], fields: fields.map((field) => ({ required: false, nullable: false, enumValues: [], enumLabels: {}, ...field })) }; }

function recommendation(source: "bsi" | "cis" | "vendor"): RecommendationRecord {
  const base = bsiRecommendation(source);
  if (source === "bsi") return base;
  if (source === "vendor") return { ...base, section: "Device passcode", recommendedValue: 8, vendor: { name: "Apple" } };
  return { ...base, benchmarkId: "DEMO-IOS", benchmarkTitle: "Sanitized iOS benchmark", benchmarkVersion: "Demo", benchmarkDate: "2026-08-31", managementSurface: "MDM", sourcePdfPath: "demo", recommendationId: "DEMO-01", profileApplicability: ["Demo"], description: base.requirementText, rationale: base.reason, impact: "Demo evidence only", audit: "Review the passcode configuration.", remediation: "Set minimum length to 8.", defaultValue: null, references: [], recommendedValue: 8 };
}
